# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ORGANIZATIONS = ["American Red Cross", "Wounded Warrior", "Save the Children", "World Wildlife Federation", "International Rescue Commitee"]
ORGS = {:"Direct Relief"=> "Direct Relief is a humanitarian aid organization, active in all 50 states and more than 80 countries, with a mission to improve the health and lives of people affected by poverty or emergencies.
  Nongovernmental, nonsectarian, and not-for-profit, Direct Relief provides assistance to people and communities without regard to politics, religion, ethnic identities or ability to pay.",
        :"The Rotary Foundation of Rotary International"=>"The Rotary Foundation is a not-for-profit corporation funded solely by voluntary contributions from members and friends of Rotary who support its mission to advance world understanding, goodwill, and peace.",
        :"Matthew 25: Ministries" => "Matthew 25 Ministries (M25M) is an international humanitarian aid and disaster relief organization helping the poorest of the poor locally, nationally and internationally regardless of race, creed or political persuasion. By rescuing and reusing products from major corporations, manufacturers, hospitals and individuals, Matthew 25: Ministries provides basic necessities, skill development and disaster relief across the US and worldwide.",
        :"Samaritan's Purse" => "Samaritan's Purse is a nondenominational evangelical Christian organization providing spiritual and physical aid to hurting people around the world. Since 1970, Samaritan's Purse has helped meet needs of people who are victims of war, poverty, natural disasters, disease, and famine with the purpose of sharing God's love through His Son, Jesus Christ. Emergency relief meets desperate needs of victims worldwide. Operation Christmas Child delivers more than 10 million shoebox gifts to poor children in more than 100 countries each year. World Medical Mission sends doctors, equipment, and supplies to underprivileged countries. Community development and vocational programs in impoverished villages and neighborhoods help people break the cycle of poverty and give them hope for a better tomorrow. Vulnerable children are rescued, educated, fed, clothed, and sheltered, letting them know that God loves them, Jesus died and rose again for them, and they are not forgotten.",
        :"The Conservation Fund" => "At The Conservation Fund, we believe that conservation should work for America. By creating solutions that make environmental and economic sense, we are re-defining conservation to demonstrate its essential role in our future prosperity. We have the highest program allocation - putting 97% of our resources toward mission - and lowest fundraising costs in our field and continue to outperform for our efficiency and effectiveness. Since 1985 we have protected more than 7.5 million acres of land, working in all 50 states; we've preserved forests, deserts, parks, waterways and every type of landscape in between. From historic places that tell the story of America to helping communities grow smarter, greener cities, our work benefits all Americans.",
        :"Cystic Fibrosis Foundation" => "The Cystic Fibrosis Foundation (CFF) was established in 1955 to assure the development of the means to cure and control cystic fibrosis (CF) and to improve the quality of life for those with the disease. The Foundation is the leading organization in the United States devoted to cystic fibrosis. It funds and accredits more than 115 CF care centers, 95 adult care programs and 50 affiliate programs, and has 80 chapters and branch offices nationwide. Cystic fibrosis is an inherited chronic disease that affects the lungs and digestive system of about 30,000 children and adults in the United States (70,000 worldwide). A defective gene and its protein product cause the body to produce unusually thick, sticky mucus.",
        :"The Carter Center" => "Founded in 1982, the Carter Center, in partnership with Emory University, is guided by a fundamental commitment to human rights and the alleviation of human suffering; it seeks to prevent and resolve conflicts, enhance freedom and democracy, and improve health. While the program agenda may change, The Carter Center is guided by five principles: it emphasizes action and results based on careful research and analysis; it does not duplicate the effective efforts of others; it addresses difficult problems and recognizes the possibility of failure as an acceptable risk; it acts as a neutral in dispute resolution activities; and it believes that people can improve their lives when provided with the necessary skills, knowledge, and access to resources.",
        :"Americares" => "Americares saves lives and improves health for people affected by poverty or disaster so they can reach their full potential. Since it was established nearly 40 years ago, Americares has provided more than $15 billion in aid to 164 countries, including the United States.",
        :"Doctors Without Borders, USA" => "Doctors Without Borders, USA (DWB-USA) was founded in 1990 in New York City to raise funds, create awareness, recruit field staff, and advocate with the United Nations and US government on humanitarian concerns. Doctors Without Borders/Médecins Sans Frontières (MSF) is an international medical humanitarian organization that provides aid in nearly 60 countries to people whose survival is threatened by violence, neglect, or catastrophe, primarily due to armed conflict, epidemics, malnutrition, exclusion from health care, or natural disasters.",
        :"HealthWell Foundation" => "The HealthWell Foundation provides financial assistance to eligible individuals to cover coinsurance, copayments, health care premiums and deductibles for certain medications and therapies. If you've been prescribed a medication and your insurance company covers it, but you still cannot afford the coinsurance or copayment required, we may be able to help you by paying for part of your costs associated with the medication. Also, if you are eligible for health insurance, but cannot afford the insurance premium, we may be able to help with your insurance premium.",
        :"Last Chance for Animals" => "Founded in 1984, Last Chance for Animals (LCA) recognizes that animals have the ability to experience pain, and as such they deserve certain basic rights protecting them from pain caused by humans. LCA believes that non-human animals should not be subjected to suffering and exploitation by humans because alternatives exist for nearly every traditional usage of animals. LCA opposes the use of animals for scientific curiosity, entertainment, clothing, and food. LCA recognizes the use of non-human animals in medical experimentation as both immoral and of questionable scientific validity due to the tremendous biological difference between species. LCA's work advocates conscious and informed lifestyle decisions, and LCA is committed to disseminating truthful information about societal animal abuse to improve the treatment of animals.",
        :"Books For Africa" => "Founded in 1988, Books for Africa (BFA) collects, sorts, ships, and distributes books to children in Africa. Our goal is to end the book famine in Africa. Books donated by publishers, schools, libraries, individuals, and organizations are sorted and packed by volunteers who carefully choose books that are age and subject appropriate. We send good books, enough books for a whole class to use. Since 1988, Books For Africa has shipped more than 35 million books to 48 African countries. They are on once-empty library shelves, in classrooms in rural schools, and in the hands of children who have never before held a book. Each book will be read over and over again. When the books arrive, they go to those who need them most: children who are hungry to read, hungry to learn, hungry to explore the world in ways that only books make possible.",
        :"India Development and Relief Fund, Inc. (IDRF)" => "IDRF's mission is to empower marginalized people with skills, services and infrastructure grounded in sustainable development. We provide support for programs that improve education, healthcare, women empowerment, governance, and eco-friendly livelihoods at grass-roots level in India, Nepal and Sri Lanka. Moreover, IDRF converts natural disasters into opportunities for long-term development of the affected communities. Our programs are implemented by carefully-vetted and experienced local NGOs."
      }
User.create(username:'VB', password:'god', role:1)

ORGS.each do |name, description|
  Organization.create!(name: name,
                       description: description)
end

